title: Niv Lab Technical Resources
author: Niv Lab
email: nivlab.princeton.edu
description: > # this means to ignore newlines until "show_exerpts:"
  Technical resources made by the Niv lab.

# Header Links
homepage: https://nivlab.princeton.edu/
github_username:  nivlab

# Build settings
theme: jekyll-theme-portfolio

plugins:
 - jekyll-feed
 - jekyll-seo-tag
