title: Niv Lab Technical Resources
author: Niv Lab
email: nivlab.princeton.edu
description: > # this means to ignore newlines until "show_exerpts:"
  Technical resources made by the Niv lab.

# Header Links
homepage: https://nivlab.princeton.edu/
#baseurl: "/nivlab"
#url: "https://nivlab.github.io"
github_username:  nivlab

# Build settings
theme: tedivm/jekyll-theme-portfolio

plugins:
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-seo-tag
