title: Niv Lab Technical Resources
author: Niv Lab
email: https://nivlab.princeton.edu
description: > # this means to ignore newlines until "show_exerpts:"
  Technical resources maintained by the Niv lab.

# Header Links
homepage: https://nivlab.princeton.edu
github_username: nivlab

plugins:
 - jekyll-feed
 - jekyll-seo-tag
